### PR TITLE
Feature/#16/proverbs crud

### PR DESCRIPTION
**Pull request by heyolajyd**

### CODE REVIEW

**Comment by akinjide** [comment]
@andela-Jaderibigbe can we fix all this comments, and also make the test pass and the conflict

**Comment by heyolajyd** [comment]
@andela-abankole Cool. I will fix the tests. This hound bot is really cool :)

**Comment by akinjide** [comment]
Cool, Can we work on the conflict as well

**Comment by innocentamadi** [comment]
What? Decreased coverage by 11.09%? Jyd what have you done?? 😀

**Comment by heyolajyd** [comment]
@andela-iamadi Can you point me to why coveralls coverage is failing?

**Comment by akinjide** [comment]
@andela-Jaderibigbe how's the coverage test coming?

**Pull request merged**
